# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR pyLoad Team
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pyLoad 0.4.5\n"
"Report-Msgid-Bugs-To: 'bugs@pyload.org'\n"
"POT-Creation-Date: 2011-03-14 16:47+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: pyLoadCore.py:166
msgid "Received Quit signal"
msgstr ""

#: pyLoadCore.py:251
#, python-format
msgid "pyLoad already running with pid %s"
msgstr ""

#: pyLoadCore.py:265
#, python-format
msgid "Failed changing group: %s"
msgstr ""

#: pyLoadCore.py:274
#, python-format
msgid "Failed changing user: %s"
msgstr ""

#: pyLoadCore.py:276
msgid "folder for logs"
msgstr ""

#: pyLoadCore.py:287
#, python-format
msgid "Using home directory: %s"
msgstr ""

#: pyLoadCore.py:293
msgid "pycrypto to decode container files"
msgstr ""

#: pyLoadCore.py:296
msgid "folder for temporary files"
msgstr ""

#: pyLoadCore.py:301
msgid "folder for downloads"
msgstr ""

#: pyLoadCore.py:302
msgid "file for links"
msgstr ""

#: pyLoadCore.py:305
msgid "OpenSSL for secure connection"
msgstr ""

#: pyLoadCore.py:309
msgid "Moving old user config to DB"
msgstr ""

#: pyLoadCore.py:312
msgid "Please check your logindata with ./pyLoadCore.py -u"
msgstr ""

#: pyLoadCore.py:334
#, python-format
msgid "Downloadtime: %s"
msgstr ""

#: pyLoadCore.py:346
#, python-format
msgid "Free space: %s"
msgstr ""

#: pyLoadCore.py:376
msgid "restarting pyLoad"
msgstr ""

#: pyLoadCore.py:380
msgid "pyLoad quits"
msgstr ""

#: pyLoadCore.py:434
#, python-format
msgid "Install %s"
msgstr ""

#: pyLoadCore.py:469
#, python-format
msgid "could not find %(desc)s: %(name)s"
msgstr ""

#: pyLoadCore.py:471
#, python-format
msgid "could not create %(desc)s: %(name)s"
msgstr ""

#: pyLoadCore.py:483
msgid "shutting down..."
msgstr ""

#: pyLoadCore.py:498
msgid "error while shutting down"
msgstr ""

#: pyLoadCore.py:632
#, python-format
msgid "Added package %(name)s containing %(count)d links"
msgstr ""

#: pyLoadCore.py:684
#, python-format
msgid "Added %(count)d links to package #%(package)d "
msgstr ""

#: pyLoadCore.py:900
msgid "killed pyLoad from Terminal"
msgstr ""

#: module/JsEngine.py:89
msgid ""
"No js engine detected, please install either Spidermonkey, ossp-js or pyv8"
msgstr ""

#: module/ThreadManager.py:94
#, python-format
msgid "Reconnect Failed: %s"
msgstr ""

#: module/ThreadManager.py:118
msgid "Reconnect script not found!"
msgstr ""

#: module/ThreadManager.py:124
msgid "Starting reconnect"
msgstr ""

#: module/ThreadManager.py:138
msgid "Failed executing reconnect script!"
msgstr ""

#: module/ThreadManager.py:150
#, python-format
msgid "Reconnected, new IP: %s"
msgstr ""

#: module/HookManager.py:50 module/HookManager.py:80
#, python-format
msgid "Error executing hooks: %s"
msgstr ""

#: module/HookManager.py:65
#, python-format
msgid "%(name)s loaded, activated %(value)s"
msgstr ""

#: module/HookManager.py:67
#, python-format
msgid "Failed activating %(name)s"
msgstr ""

#: module/CaptchaManager.py:78
msgid "No Client connected for captcha decrypting"
msgstr ""

#: module/PluginThread.py:163
#, python-format
msgid "Download skipped: %(name)s @ %(plugin)s"
msgstr ""

#: module/PluginThread.py:166
msgid "File already exists."
msgstr ""

#: module/PluginThread.py:169
#, python-format
msgid "Download starts: %s"
msgstr ""

#: module/PluginThread.py:177 module/PluginThread.py:330
#, python-format
msgid "Plugin %s is missing a function."
msgstr ""

#: module/PluginThread.py:184 module/PluginThread.py:241
#: module/PluginThread.py:349
#, python-format
msgid "Download aborted: %s"
msgstr ""

#: module/PluginThread.py:201
#, python-format
msgid "Download restarted: %s"
msgstr ""

#: module/PluginThread.py:211 module/PluginThread.py:339
#, python-format
msgid "Download is offline: %s"
msgstr ""

#: module/PluginThread.py:214 module/PluginThread.py:262
#, python-format
msgid "Download failed: %(name)s | %(msg)s"
msgstr ""

#: module/PluginThread.py:230
msgid ""
"Couldn't connect to host or connection resetted waiting 1 minute and retry."
msgstr ""

#: module/PluginThread.py:278
#, python-format
msgid "Download finished: %s"
msgstr ""

#: module/PluginThread.py:325
#, python-format
msgid "Decrypting starts: %s"
msgstr ""

#: module/PluginThread.py:342 module/PluginThread.py:363
#, python-format
msgid "Decrypting failed: %(name)s | %(msg)s"
msgstr ""

#: module/PluginThread.py:356
#, python-format
msgid "Retrying %s"
msgstr ""

#: module/PluginThread.py:456
#, python-format
msgid "Info Fetching for %(name)s failed | %(err)s"
msgstr ""

#: module/remote/ThriftBackend.py:40
msgid "Using SSL ThriftBackend"
msgstr ""

#: module/remote/XMLRPCBackend.py:28
msgid "Using SSL XMLRPCBackend"
msgstr ""

#: module/remote/XMLRPCBackend.py:32
msgid "SSL Certificates not found, fallback to auth XMLRPC server"
msgstr ""

#: module/remote/RemoteManager.py:34
#, python-format
msgid "%s: Remote backend error"
msgstr ""

#: module/remote/RemoteManager.py:72
#, python-format
msgid "Starting %(name)s: %(addr)s:%(port)s"
msgstr ""

#: module/remote/RemoteManager.py:74
#, python-format
msgid "Failed loading backend %(name)s | %(error)s"
msgstr ""

#: module/web/ServerThread.py:33
msgid "SSL certificates not found."
msgstr ""

#: module/web/ServerThread.py:37
#, python-format
msgid "Sorry, we dropped support for starting %s directly within pyLoad"
msgstr ""

#: module/web/ServerThread.py:38
msgid "You can use the threaded server which offers good performance and ssl,"
msgstr ""

#: module/web/ServerThread.py:39
#, python-format
msgid ""
"of course you can still use your existing %s with pyLoads fastcgi server"
msgstr ""

#: module/web/ServerThread.py:40
msgid "sample configs are located in the module/web/servers directory"
msgstr ""

#: module/web/ServerThread.py:47
#, python-format
msgid "Can't use %(server)s, python-flup is not installed!"
msgstr ""

#: module/web/ServerThread.py:61
msgid ""
"The simple builtin server offers no SSL, please consider using threaded "
"instead"
msgstr ""

#: module/web/ServerThread.py:63
#, python-format
msgid "Starting builtin webserver: %(host)s:%(port)d"
msgstr ""

#: module/web/ServerThread.py:68
#, python-format
msgid "Starting threaded SSL webserver: %(host)s:%(port)d"
msgstr ""

#: module/web/ServerThread.py:72
#, python-format
msgid "Starting threaded webserver: %(host)s:%(port)d"
msgstr ""

#: module/web/ServerThread.py:78
#, python-format
msgid "Starting fastcgi server: %(host)s:%(port)d"
msgstr ""

#: module/web/pyload_app.py:101
msgid "You dont have permission to access this page."
msgstr ""

#: module/web/pyload_app.py:175
msgid "Download directory not found."
msgstr ""

#: module/web/pyload_app.py:237 module/web/pyload_app.py:244
msgid "unlimited"
msgstr ""

#: module/web/pyload_app.py:239 module/web/pyload_app.py:246
msgid "not available"
msgstr ""

#: module/web/pyload_app.py:510
msgid "Run pyLoadCore.py -s to access the setup."
msgstr ""

#: module/web/json_app.py:56
#, python-format
msgid "waiting %s"
msgstr ""

#: module/plugins/Plugin.py:273
msgid ""
"Pil and tesseract not installed and no Client connected for captcha "
"decrypting"
msgstr ""

#: module/plugins/Plugin.py:277
msgid "No captcha result obtained in appropiate time by any of the plugins."
msgstr ""

#: module/plugins/Plugin.py:344 module/plugins/Plugin.py:368
#: module/plugins/hoster/Xdcc.py:236
#, python-format
msgid "Setting User and Group failed: %s"
msgstr ""

#: module/plugins/Container.py:71
msgid "File not exists."
msgstr ""

#: module/plugins/PluginManager.py:70
msgid "Crypter"
msgstr ""

#: module/plugins/PluginManager.py:71
msgid "Container"
msgstr ""

#: module/plugins/PluginManager.py:72
msgid "Hoster"
msgstr ""

#: module/plugins/PluginManager.py:74
msgid "Captcha"
msgstr ""

#: module/plugins/PluginManager.py:75
msgid "Account"
msgstr ""

#: module/plugins/PluginManager.py:76
msgid "Hook"
msgstr ""

#: module/plugins/PluginManager.py:160
#, python-format
msgid "%s has a invalid pattern."
msgstr ""

#: module/plugins/PluginManager.py:292
#, python-format
msgid "Error importing %(name)s: %(msg)s"
msgstr ""

#: module/plugins/PluginManager.py:293
msgid "You should fix dependicies or deactivate load on startup."
msgstr ""

#: module/plugins/AccountManager.py:85
msgid "Account settings deleted, due to new config format."
msgstr ""

#: module/plugins/Account.py:53 module/plugins/Account.py:57
#, python-format
msgid "Could not login with %(plugin)s account %(user)s | %(msg)s"
msgstr ""

#: module/plugins/Account.py:53
msgid "Wrong Password"
msgstr ""

#: module/plugins/Account.py:172
#, python-format
msgid "Your Time %s has wrong format, use: 1:22-3:44"
msgstr ""

#: module/plugins/Account.py:209
#, python-format
msgid ""
"%(plugin)s Account %(user)s has not enough traffic, checking again in 30min"
msgstr ""

#: module/plugins/Account.py:215
#, python-format
msgid "%(plugin)s Account %(user)s is expired, checking again in 1h"
msgstr ""

#: module/plugins/crypter/SerienjunkiesOrg.py:123
msgid "Downloadlimit reached"
msgstr ""

#: module/plugins/hooks/ClickAndLoad.py:73
msgid "Click'N'Load: Port 9666 already in use"
msgstr ""

#: module/plugins/hooks/UnRar.py:120
#, python-format
msgid "starting Unrar of %s"
msgstr ""

#: module/plugins/hooks/UnRar.py:149 module/plugins/hooks/UnRar.py:180
#, python-format
msgid "Unrar of %s failed (wrong password)"
msgstr ""

#: module/plugins/hooks/UnRar.py:155
#, python-format
msgid "Unrar of %s failed (missing volume)"
msgstr ""

#: module/plugins/hooks/UnRar.py:159 module/plugins/hooks/UnRar.py:176
#, python-format
msgid "Unrar of %s ok"
msgstr ""

#: module/plugins/hooks/UnRar.py:164 module/plugins/hooks/UnRar.py:172
#, python-format
msgid "Unrar of %s failed"
msgstr ""

#: module/plugins/hooks/UnRar.py:167
#, python-format
msgid ""
"Your ram amount of %s MB seems not sufficient to unrar this file. You can "
"deactivate this warning and risk instability"
msgstr ""

#: module/plugins/hooks/CaptchaTrader.py:116
msgid "Your CaptchaTrader Account has not enough credits"
msgstr ""

#: module/plugins/hooks/IRCInterface.py:72
#: module/plugins/hooks/XMPPInterface.py:76
#: module/database/FileDatabase.py:486
#, python-format
msgid "Package finished: %s"
msgstr ""

#: module/plugins/hooks/IRCInterface.py:79
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s "
msgstr ""

#: module/plugins/hooks/IRCInterface.py:91
#, python-format
msgid "New Captcha Request: %s"
msgstr ""

#: module/plugins/hooks/IRCInterface.py:92
#, python-format
msgid "Answer with 'c %s text on the captcha'"
msgstr ""

#: module/plugins/hooks/XMPPInterface.py:83
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s"
msgstr ""

#: module/plugins/hooks/HotFolder.py:82
#, python-format
msgid "Added %s from HotFolder"
msgstr ""

#: module/plugins/hooks/ExternalScripts.py:48
#: module/plugins/hooks/ExternalScripts.py:49
msgid "folders for scripts"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:44
msgid "*** Plugins have been updated, please restart pyLoad ***"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:46
msgid "No plugin updates available"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:54
msgid "No Updates for pyLoad"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:57
#, python-format
msgid "***  New pyLoad Version %s available  ***"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:58
msgid "***  Get it here: http://pyload.org/download  ***"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:61
#: module/plugins/hooks/UpdateManager.py:71
msgid "Not able to connect server for updates"
msgstr ""

#: module/plugins/hooks/UpdateManager.py:96
#, python-format
msgid "New version of %(type)s|%(name)s : %(version).2f"
msgstr ""

#: module/plugins/hoster/MegauploadCom.py:97
#, python-format
msgid "Megaupload: waiting %d minutes"
msgstr ""

#: module/plugins/hoster/MegauploadCom.py:120
msgid "You should enable direct Download in your Megaupload Account settings"
msgstr ""

#: module/plugins/hoster/MegauploadCom.py:131
msgid "You need premium to download files larger than 1 GB"
msgstr ""

#: module/plugins/hoster/MegauploadCom.py:136
msgid "The file is password protected, enter a password and restart."
msgstr ""

#: module/plugins/hoster/MegauploadCom.py:153
msgid "Megaupload is currently blocking your IP. Try again later, manually."
msgstr ""

#: module/plugins/hoster/MegauploadCom.py:225
msgid ""
"Looks like the file is still not available. Retry downloading later, "
"manually."
msgstr ""

#: module/plugins/hoster/MegauploadCom.py:228
msgid "Wrong password for download link."
msgstr ""

#: module/plugins/hoster/UploadedTo.py:76
#: module/plugins/hoster/RapidshareCom.py:141
#, python-format
msgid "%s: Not enough traffic left"
msgstr ""

#: module/plugins/hoster/UploadedTo.py:79
msgid "Traffic exceeded"
msgstr ""

#: module/plugins/hoster/UploadedTo.py:85
msgid "Deactivate direct downloads in your Uploaded.to Account settings."
msgstr ""

#: module/plugins/hoster/RapidshareCom.py:99
msgid "Rapidshare: Traffic Share (direct download)"
msgstr ""

#: module/plugins/hoster/RapidshareCom.py:129
#: module/plugins/hoster/RapidshareCom.py:199
msgid "Already downloading from this ip address, waiting 60 seconds"
msgstr ""

#: module/plugins/hoster/RapidshareCom.py:133
msgid "Invalid Auth Code, download will be restarted"
msgstr ""

#: module/plugins/hoster/RapidshareCom.py:203
msgid "RapidShareCom: No free slots"
msgstr ""

#: module/plugins/hoster/RapidshareCom.py:206
msgid "You need a premium account for this file"
msgstr ""

#: module/plugins/hoster/FilesMailRu.py:99
msgid "There was HTML Code in the Downloaded File("
msgstr ""

#: module/plugins/hoster/NetloadIn.py:142
#: module/plugins/hoster/NetloadIn.py:162
msgid "File temporarily not available"
msgstr ""

#: module/plugins/hoster/NetloadIn.py:177
#, python-format
msgid "Netload: waiting between downloads %d s."
msgstr ""

#: module/plugins/hoster/NetloadIn.py:207
#, python-format
msgid "Netload: waiting for captcha %d s."
msgstr ""

#: module/plugins/hoster/NetloadIn.py:246
msgid "Downloaded File was empty"
msgstr ""

#: module/plugins/container/LinkList.py:54
msgid "LinkList could not be cleared."
msgstr ""

#: module/plugins/accounts/MegauploadCom.py:43
msgid "Activate direct Download in your MegaUpload Account"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "finished"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "offline"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "online"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "queued"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "checking"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "waiting"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "reconnected"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "starting"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "failed"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "aborted"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "decrypting"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "custom"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "downloading"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "processing"
msgstr ""

#: module/database/FileDatabase.py:53
msgid "unknown"
msgstr ""

#: module/database/DatabaseBackend.py:174
msgid "Filedatabase was deleted due to incompatible version."
msgstr ""

#: module/database/DatabaseBackend.py:189
msgid "Filedatabase could NOT be converted."
msgstr ""

#: module/database/DatabaseBackend.py:198
msgid "Database was converted from v2 to v3."
msgstr ""

#: module/database/DatabaseBackend.py:206
msgid "Database was converted from v3 to v4."
msgstr ""

#: module/database/DatabaseBackend.py:223
msgid "Converting old Django DB"
msgstr ""

#: module/database/DatabaseBackend.py:240
msgid "Moving users"
msgstr ""
